apiVersion: apps/v1
kind: Deployment
metadata:
  name: userjobexecuter
  labels:
    app: userjobexecuter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userjobexecuter
  template:
    metadata:
      labels:
        app: userjobexecuter
    spec:
     # hostNetwork: true
      #dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: userjobexecuter
          image: 133194539480.dkr.ecr.us-east-1.amazonaws.com/userjobexecuter-dev
          ports:
            - containerPort: 6666
---
apiVersion: v1
kind: Service
metadata:
  name: userjobexecuter
spec:
  selector:
    app: userjobexecuter
  ports:
    - protocol: TCP
      port: 6666
      targetPort: 6666
